In [0]:
import numpy as np # Imports numpy as a variable "np"

nums = [1, 2, 3, 4, 5] # Simple python list of ints

arr = np. array(nums) # Typecasts from Python list to numpy arry

nums_2 = [range(1,5), range(5,9)] # Sets of a list of 2 lists aka 2D List

arr_2 = np.array(nums_2) # Typecasts from a Python list to a numpy array

print(arr_2)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5]


In [0]:
print(np.zeros(10)) # Displays a row of 10 * "0"
print(np.zeros((3,6))) # Displays a 3 x 6 matrix of "0"
print(np.ones(10)) # Displays a row of 10 * "1"
print(np.linspace(0, 1, 5)) # Displays 5 even intervals from 0 - 1
print(np.logspace(0, 3, 4)) # Displays 10**n power where n in range(4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0.   0.25 0.5  0.75 1.  ]
[   1.   10.  100. 1000.]


In [0]:
arr = arr.astype(float) # Converts each data element to a float
print(arr.dtype) # .dtype returns the data type of ea el in the array
print(arr_2.dtype)
print(arr.ndim) # Displays the number of m=rows
print(arr_2.shape) # Displays the m=rows x n=cols of the given array
print(arr.size) # Displays the number of n=cols
print(len(arr_2)) # Displays the len of the outermost specified array

float64
int64
1
(2, 4)
5
2


In [0]:
arr = np.arange(10, dtype=float).reshape((2,5))
# Instantiates an numpy array of 10 float elements in a m=2 x n=5 matrix
print(arr.shape) # Displays the m=rows x n=cols of the given array
print(arr.reshape(5,2)) # Rearranges an 2 x 5 matrix into an m=2 x n=5 matrix

(2, 5)
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [0]:
a = np.array([0, 1]) # Instantiates an array from the input list.
a_col = a[:, np.newaxis] # Takes all el's from a and converts them into a col
print(a_col)
print(a_col.T)
arr_flt = arr.flatten() # Puts the input array into a singular row
arr_flt[0] = 33 # Changes the first value to '33'
print(arr_flt)
print(arr)
arr_flt = arr.ravel()
arr_flt[0] = 33 # Changes the first value to '33'. The significance here is
# that, because arr_flt is a reference to the same memory space as arr, when
# a value is changed in either reference, the value stored in memory is changed
# meaning that both arrays now refer to the same changed value. DANGER!!!!
print(arr_flt)

[[0]
 [1]]
[[0 1]]
[33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [0]:
a = np.array(np.arange(2)) # Instantiates an array with '0, 1' inside
b = np.array(np.arange(2, 4)) # Instantiates an array with '2, 3' inside
ab = np.stack((a, b)) # Places both arrays into a new array with one stacked on
# top of the other.
print(ab)
ab = ab.T # Converts each row to cols in the output array.
print(ab)

[[0 1]
 [2 3]]
[[0 2]
 [1 3]]


In [0]:
print(arr)
print(arr[0, :]) # Displays the first row in the input array
print(arr[:, 0]) # Displays the first el in each row of the input array
print(arr[:, :2]) # Displays the el's from 0 - 2 in ea row
print(arr[:, 2:]) # Displays the el's from 2 - end in ea row
arr_2 = arr[:, 1:4] # Returns the el's from 1 - 3 in ea row
print(arr_2)
arr_2[0][0] = 33 # Accesses the first el in the first row and assigns '33'
# which changes that element in arr and arr_2
print(arr_2)
print(arr)
print(arr[0, :: -1]) # Displays the reversed first row

[[33.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]
[33.  1.  2.  3.  4.]
[33.  5.]
[[33.  1.]
 [ 5.  6.]]
[[2. 3. 4.]
 [7. 8. 9.]]
[[1. 2. 3.]
 [6. 7. 8.]]
[[33.  2.  3.]
 [ 6.  7.  8.]]
[[33. 33.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]
[ 4.  3.  2. 33. 33.]


In [0]:
arr_2 = arr[:, [1, 2, 3]] # Returns the element at each index in each row of
# the index specified in the list arg
print(arr_2)
arr_2[0, 0] = 44 # Sets the first el in the first row to 44. This is to 
# demonstrate that this method of copying an array ensures that the new array
# is an entirely different array and not a copy of the original reference.
print(arr_2)
arr_2 = arr[arr > 5] # Returns all elements '> 5'
print(arr_2)
arr_2[0] = 44 # Changes the first element to '44'
print(arr_2)
print(arr)

names = np.array(['Bob', 'Joe', 'Will', 'Bob'])
# Instantiates an array of names
names == 'Bob' # Piecewise comparison against the provided string which returns
# 'True' or 'False' based on the boolean comparison into a new array.
print(names == 'Bob')
names[names != 'Bob'] = 'Joe' # Sets any names '!=' 'Bob' = 'Joe'
print(names)
print(np.unique(names)) # Returns a set of the values

[[33.  2.  3.]
 [ 6.  7.  8.]]
[[44.  2.  3.]
 [ 6.  7.  8.]]
[33. 33.  6.  7.  8.  9.]
[44. 33.  6.  7.  8.  9.]
[[33. 33.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]
[ True False False  True]
['Bob' 'Joe' 'Joe' 'Bob']
['Bob' 'Joe']


In [0]:
nums = np.arange(5) # Insantiates an array from 0 - 4
print(nums*10) # Piecewise multiplication
print(np.sqrt(nums*10)) # Piecewise sqrt
nums = np.floor(np.sqrt(nums*10)) # Rounds each el down if it has floating ints
# after the decimal
print(nums)
print(np.isnan(nums)) # Returns a piecewise comparison of whether ea el
# 'is not a number' as a new array.
print(nums + np.arange(5)) # Piecewise addition of the new array
print(np.maximum(nums, np.array([1, -2, 3, -4, 5])))
# Displays the maximum at each index among the two arrays
vec_1 = np.random.randn(10) # Generates random nums over a normal distribution
# and then randomly selects 10 nums from that distribution
vec_2 = np.random.randn(10) 
dist = np.sqrt(np.sum((vec_1 - vec_2) **2))
# Computes the distribution of the two arrays.
print(dist)

rnd = np.random.randn(4, 2) # Returns a 4x2 array of randomly selected randomly
# generated nums over a normal distribution and arranges them into a 4 x 2 matrix
print(rnd)
print(rnd.mean()) # Computes the mean of the entire matrix
print(rnd.std()) # Computes the std of the entire matrix
print(rnd.argmin()) # Returns the index of the min element counting from
# rnd[0, 0] - rnd[end, end]
print(rnd.sum()) # Returns the sum of the entire matrix
print(rnd.sum(axis=0)) # Returns the sum of ea cols
print(rnd.sum(axis=1)) # Returns the sum of ea row
print((rnd > 0).sum()) # Returns the sum of all el's '> 0'
print((rnd > 0).any()) # Returns a bool if any el's '> 0'
print((rnd > 0).all()) # Returns a bool if all el's '> 0'
np.random.seed(1234) # Sets the seed param for the random module
print(np.random.rand(2,3)) # Returns a 2 x 3 matrix of randomly selected nums
print(np.random.randn(10)) # Returns a row of 10 randomly selected nums from
# a normal distribution of nums
print(np.random.randint(0, 2, 10)) # Returns a row of 10 el's of randomly
# selected integers between 0 - 1 (i.e. 0 or 1)

[ 0 10 20 30 40]
[0.         3.16227766 4.47213595 5.47722558 6.32455532]
[0. 3. 4. 5. 6.]
[False False False False False]
[ 0.  4.  6.  8. 10.]
[1. 3. 4. 5. 6.]
2.7998504192208746
[[-1.89610087  0.68386223]
 [-1.00655134  0.00769448]
 [ 1.23084078  2.00074455]
 [-0.6721939   0.91388772]]
0.15777295508673345
1.2084036788297992
0
1.2621836406938676
[-2.34400533  3.60618897]
[-1.21223864 -0.99885686  3.23158533  0.24169382]
5
True
False
[[0.19151945 0.62210877 0.43772774]
 [0.78535858 0.77997581 0.27259261]]
[ 8.59588414e-01 -6.36523504e-01  1.56963721e-02 -2.24268495e+00
  1.15003572e+00  9.91946022e-01  9.53324128e-01 -2.02125482e+00
 -3.34077366e-01  2.11836468e-03]
[0 0 0 1 1 1 0 1 1 0]


In [0]:
a = np.zeros((4, 3)) # Sets up a 4 x 3 matrix of '0'
for i in range(1, len(a)): # Changes each el in each row to a multiple of '10'
    # based on its index 'i'
    a[i] = np.ones(3)*(10 * i)
b = np.array(np.arange(3)) # Returns an array with ' 0, 1, 2' inside
print(a + b) # Displays the numpy property that allows matrices of differing
# dimensions to be added
print(np.shape(a + b)) # Displays the m=rows x n=cols dimensions of the array

[[ 0.  1.  2.]
 [10. 11. 12.]
 [20. 21. 22.]
 [30. 31. 32.]]
(4, 3)


In [0]:
X = np.random.randn(4, 2)
min_val = np.min(X, axis=0)
print(X, "\n")
print(min_val, "\n")

def standardize(X):
    col_mean = np.mean(X, axis=0)
    col_std = np.std(X, axis=0)
    return (X - col_mean)/col_std

print(standardize(X))
    

[[ 1.35835198 -0.28694235]
 [ 0.44143825 -0.76987271]
 [-0.97456841  0.70900741]
 [-0.10578273  0.77677573]] 

[-0.97456841 -0.76987271] 

[[ 1.39090516 -0.59850264]
 [ 0.30872572 -1.33175114]
 [-1.3625038   0.91367949]
 [-0.33712707  1.01657429]]


PAGE 7.

TASK: Describe in detail, what is happening in the diagram on page 7 of the handout.

The firs step that numpy/python takes to execute the commands given is to compare the shape of each of the input matrices.
i.e. how many rows and cols in Array_1 vs Array_2. If there is a mismatch, python, through the numpy module, knows to check
if one of the dimensions of the smaller matrix can stretch to match the smallest dimension of the larger matrix. This continues
until the dimensions of the larger matrix are exhausted as well. The example provided shows:

            
            [[0,   0,  0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]]
            
                           +
                           
              [0, 1, 2]
              
              whereby:
              
              [0, 0, 0] + [0, 1, 2] = [0, 1, 2] and so on until the larger matrix has had the smaller
              matrix added to each of its rows.   
            
            
            
            
            

np.zeros/ones : These are useful to assist in rapid creation of placeholder values within initial matrices for intializing necessary computational value matrices. i.e. theta values, identity matrices, etc...

np.arange: This command rapidly intializes an array over a given range. This can be useful when instantiating a new array with default values.

np.reshape: This command is another option for transforming a matrix so that computational and other operations may be executed properly. For example, when normalizing features.

np.min/max/mean/std/sum: All of thes commands allow the programmer to find computational values necessary to build probability algorithms aimed at machine learning purposes. These commands are also customizable along axes making them even more useful as the complexity of neural network computations expand.

np.array([some_list]).T: This accomplishes in one line of code what might have taken a skilled programmer several minutes as well as programming space to accomplish allowing the programmer to stay focused on problem-solving rather than getting lost in the code.